name: 'Check PR body'
description: 'Check PR body for words (e.g.: JIRA links) for specific authors'
author: 'Deeds'
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
inputs:
  authorsToCheck:
    description: 'A csv string of specific authors that this action will apply to'
  jiraString:
    description: 'Word/String that should not be in the PR body, can be left blank (no functionality will occur)'
  github-token:
    description: 'Github token, added automagically'
runs:
  using: 'node16'
  main: 'dist/index.js'